# Script to update superadmin password hash in database
# This generates the correct hash format using the PasswordHasher service

$connectionString = "Server=localhost;Database=ClinicCare_Global;User Id=ClinicCareUser;Password=ClinicCare@2024;TrustServerCertificate=true"

# Generate password hash using a C# snippet
# The PasswordHasher uses: Base64(salt(32 bytes) + hash(32 bytes))
# We'll use a known working hash for "Admin@123"

# For now, let's create a simple SQL update that uses a hash generated by the application
# You need to run this after generating the hash using the PasswordHasher

Write-Host "To update the password hash:" -ForegroundColor Yellow
Write-Host "1. Run the application" -ForegroundColor Yellow
Write-Host "2. Use Swagger to call a test endpoint that generates the hash" -ForegroundColor Yellow
Write-Host "3. Or use the SQL script below with the generated hash" -ForegroundColor Yellow
Write-Host ""
Write-Host "SQL Update Command:" -ForegroundColor Green
Write-Host "UPDATE ClinicCare_Global.dbo.SystemUsers" -ForegroundColor Cyan
Write-Host "SET PasswordHash = '<GENERATED_HASH_HERE>'" -ForegroundColor Cyan
Write-Host "WHERE Email = 'superadmin@cliniccare.com';" -ForegroundColor Cyan

