import { useState } from 'react'
import { Button, Table, Tag, Space, Input, Modal, Form, InputNumber, Select, Popconfirm, AutoComplete } from 'antd'
import { PlusOutlined, EditOutlined, DeleteOutlined, SearchOutlined, ImportOutlined } from '@ant-design/icons'
import { useQuery } from '@tanstack/react-query'
import { useClinicMedicines, useCreateClinicMedicine, useUpdateClinicMedicine, useDeleteClinicMedicine, useAddClinicMedicineFromGlobal } from '@core/hooks/queries/useClinicMedicines'
import { globalMedicineService } from '@core/services/globalMedicineService'
import { useClinics } from '@core/hooks/queries/useClinics'
import { useDebouncedValue } from '@core/hooks/useDebouncedValue'
import type { ClinicMedicine } from '@core/services/clinicMedicineService'
import dayjs from 'dayjs'

const { Option } = Select

const MEDICINE_TYPES = ['Tablet', 'Capsule', 'Syrup', 'Injection', 'Cream', 'Drops', 'Inhaler', 'Other']

export const ClinicMedicinesPage = () => {
  const [searchText, setSearchText] = useState('')
  const [selectedClinicId, setSelectedClinicId] = useState<number | undefined>()
  const [isActiveFilter, setIsActiveFilter] = useState<boolean | undefined>(true) // Default to active only
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [isAddFromGlobalModalOpen, setIsAddFromGlobalModalOpen] = useState(false)
  const [editingMedicine, setEditingMedicine] = useState<ClinicMedicine | null>(null)
  const [form] = Form.useForm()
  const [addFromGlobalForm] = Form.useForm()
  const [globalSearchTerm, setGlobalSearchTerm] = useState('')
  const debouncedGlobalSearch = useDebouncedValue(globalSearchTerm, 300)

  const { data: clinics } = useClinics()
  const { data: medicines, isLoading } = useClinicMedicines({
    searchTerm: searchText || undefined,
    clinicId: selectedClinicId,
    isActive: isActiveFilter
  })

  const { data: globalMedicines = [] } = useQuery({
    queryKey: ['global-medicines-search', debouncedGlobalSearch],
    queryFn: () => globalMedicineService.getAll({ searchTerm: debouncedGlobalSearch || undefined }),
    enabled: isAddFromGlobalModalOpen && debouncedGlobalSearch.length >= 2
  })

  const createMutation = useCreateClinicMedicine()
  const updateMutation = useUpdateClinicMedicine()
  const deleteMutation = useDeleteClinicMedicine()
  const addFromGlobalMutation = useAddClinicMedicineFromGlobal()

  const handleCreate = () => {
    setEditingMedicine(null)
    form.resetFields()
    setIsModalOpen(true)
  }

  const handleAddFromGlobal = () => {
    addFromGlobalForm.resetFields()
    setGlobalSearchTerm('')
    setIsAddFromGlobalModalOpen(true)
  }

  const handleEdit = (medicine: ClinicMedicine) => {
    setEditingMedicine(medicine)
    
    // Check if the existing name matches the auto-generated format
    const autoGenerated = generateMedicineName(
      medicine.genericName || '',
      medicine.potency || '',
      medicine.manufacturer || ''
    )
    const isAutoGenerated = medicine.name === autoGenerated
    
    form.setFieldsValue({
      ...medicine,
      clinicId: medicine.clinicId,
      _nameManuallyEdited: !isAutoGenerated // Only mark as manually edited if it doesn't match auto-generated format
    })
    setIsModalOpen(true)
  }

  // Auto-generate Medicine Name from Generic Name, Potency, and Manufacturer
  const generateMedicineName = (genericName: string, potency: string, manufacturer: string): string => {
    const parts = [genericName, potency, manufacturer].filter(part => part && part.trim())
    return parts.join(' ')
  }

  const handleFormValuesChange = (changedValues: any, allValues: any) => {
    // Track if Medicine Name was manually edited
    const isNameManuallyEdited = form.getFieldValue('_nameManuallyEdited') === true
    
    // Auto-generate Medicine Name when Generic Name, Potency, or Manufacturer changes
    if (changedValues.genericName !== undefined || changedValues.potency !== undefined || changedValues.manufacturer !== undefined) {
      const genericName = allValues.genericName || ''
      const potency = allValues.potency || ''
      const manufacturer = allValues.manufacturer || ''
      
      // Only auto-generate if Medicine Name wasn't manually edited
      if (!isNameManuallyEdited) {
        const newName = generateMedicineName(genericName, potency, manufacturer)
        form.setFieldsValue({ name: newName })
      }
    }
    
    // Track manual edits to Medicine Name
    if (changedValues.name !== undefined) {
      const currentName = changedValues.name || ''
      const genericName = allValues.genericName || ''
      const potency = allValues.potency || ''
      const manufacturer = allValues.manufacturer || ''
      const autoGenerated = generateMedicineName(genericName, potency, manufacturer)
      
      // If user manually changed the name to something different from auto-generated, mark it as manually edited
      if (currentName !== autoGenerated) {
        form.setFieldsValue({ _nameManuallyEdited: true })
      } else {
        form.setFieldsValue({ _nameManuallyEdited: false })
      }
    }
  }

  const handleDelete = (id: number) => {
    deleteMutation.mutate(id)
  }

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      
      if (editingMedicine) {
        updateMutation.mutate({ id: editingMedicine.id, data: values })
        setIsModalOpen(false)
        setEditingMedicine(null)
      } else {
        createMutation.mutate(values as any)
        setIsModalOpen(false)
      }
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  const handleAddFromGlobalSubmit = async () => {
    try {
      const values = await addFromGlobalForm.validateFields()
      addFromGlobalMutation.mutate({
        globalMedicineId: values.globalMedicineId,
        clinicId: values.clinicId,
        purchasePrice: values.purchasePrice,
        sellingPrice: values.sellingPrice
      })
      setIsAddFromGlobalModalOpen(false)
    } catch (error) {
      console.error('Validation failed:', error)
    }
  }

  // Backend already handles filtering, so we can use medicines directly
  const filteredMedicines = medicines || []

  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      sorter: (a: ClinicMedicine, b: ClinicMedicine) => a.name.localeCompare(b.name)
    },
    {
      title: 'Generic Name',
      dataIndex: 'genericName',
      key: 'genericName'
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => <Tag color="blue">{type}</Tag>
    },
    {
      title: 'Potency',
      dataIndex: 'potency',
      key: 'potency'
    },
    {
      title: 'Manufacturer',
      dataIndex: 'manufacturer',
      key: 'manufacturer'
    },
    {
      title: 'Clinic',
      dataIndex: 'clinicName',
      key: 'clinicName'
    },
    {
      title: 'Purchase Price',
      dataIndex: 'purchasePrice',
      key: 'purchasePrice',
      render: (price: number) => `$${price.toFixed(2)}`,
      sorter: (a: ClinicMedicine, b: ClinicMedicine) => a.purchasePrice - b.purchasePrice
    },
    {
      title: 'Selling Price',
      dataIndex: 'sellingPrice',
      key: 'sellingPrice',
      render: (price: number) => `$${price.toFixed(2)}`,
      sorter: (a: ClinicMedicine, b: ClinicMedicine) => a.sellingPrice - b.sellingPrice
    },
    {
      title: 'Status',
      dataIndex: 'isActive',
      key: 'isActive',
      render: (isActive: boolean) => (
        <Tag color={isActive ? 'green' : 'red'}>
          {isActive ? 'Active' : 'Inactive'}
        </Tag>
      )
    },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => dayjs(date).format('MMM DD, YYYY')
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 150,
      render: (_: any, record: ClinicMedicine) => (
        <Space>
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
            size="small"
          >
            Edit
          </Button>
          <Popconfirm
            title="Are you sure you want to delete this medicine?"
            onConfirm={() => handleDelete(record.id)}
            okText="Yes"
            cancelText="No"
          >
            <Button
              type="link"
              danger
              icon={<DeleteOutlined />}
              size="small"
            >
              Delete
            </Button>
          </Popconfirm>
        </Space>
      )
    }
  ]

  return (
    <div style={{ padding: '24px' }}>
      <div style={{ marginBottom: '24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: '24px', fontWeight: 600 }}>Clinic Medicines</h1>
          <p style={{ margin: '8px 0 0 0', color: '#666' }}>
            Manage your clinic's medicine catalog
          </p>
        </div>
        <Space>
          <Button
            type="default"
            icon={<ImportOutlined />}
            onClick={handleAddFromGlobal}
          >
            Add from Global Catalog
          </Button>
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={handleCreate}
          >
            Add New Medicine
          </Button>
        </Space>
      </div>

      <div style={{ marginBottom: '16px', display: 'flex', gap: '16px' }}>
        <Input
          placeholder="Search medicines..."
          prefix={<SearchOutlined />}
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
          style={{ maxWidth: '300px' }}
          allowClear
        />
        <Select
          placeholder="Filter by clinic"
          style={{ width: 200 }}
          allowClear
          value={selectedClinicId}
          onChange={setSelectedClinicId}
        >
          {clinics?.map(clinic => (
            <Option key={clinic.id} value={clinic.id}>{clinic.name}</Option>
          ))}
        </Select>
        <Select
          placeholder="Status"
          style={{ width: 150 }}
          value={isActiveFilter === undefined ? 'all' : isActiveFilter ? 'active' : 'inactive'}
          onChange={(value) => {
            if (value === 'all') setIsActiveFilter(undefined)
            else if (value === 'active') setIsActiveFilter(true)
            else setIsActiveFilter(false)
          }}
        >
          <Option value="active">Active</Option>
          <Option value="inactive">Inactive</Option>
          <Option value="all">All</Option>
        </Select>
      </div>

      <Table
        columns={columns}
        dataSource={filteredMedicines}
        loading={isLoading}
        rowKey="id"
        pagination={{
          pageSize: 10,
          showSizeChanger: true,
          showTotal: (total) => `Total ${total} medicines`
        }}
      />

      {/* Create/Edit Medicine Modal */}
      <Modal
        title={editingMedicine ? 'Edit Medicine' : 'Add New Medicine'}
        open={isModalOpen}
        onOk={handleSubmit}
        onCancel={() => {
          setIsModalOpen(false)
          setEditingMedicine(null)
          form.resetFields()
          form.setFieldsValue({ _nameManuallyEdited: false })
        }}
        confirmLoading={createMutation.isPending || updateMutation.isPending}
        width={600}
      >
        <Form
          form={form}
          layout="vertical"
          style={{ marginTop: '24px' }}
          onValuesChange={handleFormValuesChange}
        >
          <Form.Item
            label="Clinic"
            name="clinicId"
            rules={[{ required: true, message: 'Please select a clinic' }]}
          >
            <Select placeholder="Select clinic" disabled={!!editingMedicine}>
              {clinics?.map(clinic => (
                <Option key={clinic.id} value={clinic.id}>{clinic.name}</Option>
              ))}
            </Select>
          </Form.Item>

          <Form.Item
            label="Generic Name"
            name="genericName"
            rules={[{ required: true, message: 'Please enter generic name' }]}
            tooltip="Standard homeopathic/Latin name (e.g., 'Nux vomica', 'Arnica montana')"
          >
            <Input placeholder="e.g., Nux vomica" />
          </Form.Item>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
            <Form.Item
              label="Type"
              name="type"
              rules={[{ required: true, message: 'Please select type' }]}
            >
              <Select placeholder="Select type">
                {MEDICINE_TYPES.map(type => (
                  <Option key={type} value={type}>{type}</Option>
                ))}
              </Select>
            </Form.Item>

            <Form.Item
              label="Potency"
              name="potency"
              rules={[{ required: true, message: 'Please enter potency' }]}
            >
              <Input placeholder="e.g., 30C, 200C" />
            </Form.Item>
          </div>

          <Form.Item
            label="Manufacturer"
            name="manufacturer"
            rules={[{ required: true, message: 'Please enter manufacturer' }]}
          >
            <Input placeholder="e.g., SBL, Dr. Reckeweg" />
          </Form.Item>

          <Form.Item
            label="Medicine Name"
            name="name"
            rules={[{ required: true, message: 'Please enter medicine name' }]}
            tooltip="Auto-generated from Generic Name, Potency, and Manufacturer. You can edit if needed."
          >
            <Input placeholder="Auto-generated (editable)" />
          </Form.Item>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
            <Form.Item
              label="Purchase Price"
              name="purchasePrice"
              rules={[{ required: true, message: 'Please enter purchase price' }]}
            >
              <InputNumber
                min={0}
                step={0.01}
                style={{ width: '100%' }}
                prefix="$"
                placeholder="0.00"
              />
            </Form.Item>

            <Form.Item
              label="Selling Price"
              name="sellingPrice"
              rules={[{ required: true, message: 'Please enter selling price' }]}
            >
              <InputNumber
                min={0}
                step={0.01}
                style={{ width: '100%' }}
                prefix="$"
                placeholder="0.00"
              />
            </Form.Item>
          </div>

          <Form.Item
            label="Description"
            name="description"
          >
            <Input.TextArea rows={3} placeholder="Optional description" />
          </Form.Item>
        </Form>
      </Modal>

      {/* Add from Global Catalog Modal */}
      <Modal
        title="Add Medicine from Global Catalog"
        open={isAddFromGlobalModalOpen}
        onOk={handleAddFromGlobalSubmit}
        onCancel={() => {
          setIsAddFromGlobalModalOpen(false)
          addFromGlobalForm.resetFields()
          setGlobalSearchTerm('')
        }}
        confirmLoading={addFromGlobalMutation.isPending}
        width={600}
      >
        <Form
          form={addFromGlobalForm}
          layout="vertical"
          style={{ marginTop: '24px' }}
        >
          <Form.Item
            label="Clinic"
            name="clinicId"
            rules={[{ required: true, message: 'Please select a clinic' }]}
          >
            <Select placeholder="Select clinic">
              {clinics?.map(clinic => (
                <Option key={clinic.id} value={clinic.id}>{clinic.name}</Option>
              ))}
            </Select>
          </Form.Item>

          <Form.Item
            label="Search Global Medicines"
            name="globalMedicineId"
            rules={[{ required: true, message: 'Please select a medicine' }]}
          >
            <AutoComplete
              placeholder="Search global medicine catalog..."
              options={globalMedicines.map(med => ({
                value: med.id,
                label: (
                  <div>
                    <div style={{ fontWeight: 500 }}>{med.name}</div>
                    <div style={{ fontSize: '12px', color: '#666' }}>
                      {med.genericName} - {med.type} - {med.potency}
                    </div>
                    <div style={{ fontSize: '12px', color: '#999' }}>{med.manufacturer}</div>
                  </div>
                ),
                medicine: med
              }))}
              onSearch={setGlobalSearchTerm}
              onSelect={(value, option) => {
                const selectedMedicine = (option as any).medicine
                if (selectedMedicine) {
                  addFromGlobalForm.setFieldsValue({
                    globalMedicineId: selectedMedicine.id,
                    purchasePrice: selectedMedicine.price,
                    sellingPrice: selectedMedicine.price
                  })
                }
              }}
              filterOption={false}
              style={{ width: '100%' }}
            />
          </Form.Item>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
            <Form.Item
              label="Purchase Price"
              name="purchasePrice"
            >
              <InputNumber
                min={0}
                step={0.01}
                style={{ width: '100%' }}
                prefix="$"
                placeholder="Auto-filled from global"
              />
            </Form.Item>

            <Form.Item
              label="Selling Price"
              name="sellingPrice"
            >
              <InputNumber
                min={0}
                step={0.01}
                style={{ width: '100%' }}
                prefix="$"
                placeholder="Auto-filled from global"
              />
            </Form.Item>
          </div>
        </Form>
      </Modal>
    </div>
  )
}

